//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 08:22:42 AM GMT 
//


package uk.gov.govtalk.drs.documentupload.documentupload_request;

import uk.gov.govtalk.drs.common.metadata.DRSMetaDataDefnUD;
import uk.gov.govtalk.drs.common.request.DRSRequestHeader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.govtalk.gov.uk/drs/common/request}DRS_Request_Header"/>
 *         &lt;element name="body">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Metadata" type="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_UD"/>
 *                   &lt;element name="MimeType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="application/msword"/>
 *                         &lt;enumeration value="application/vnd.ms-excel"/>
 *                         &lt;enumeration value="application/vnd.ms-powerpoint"/>
 *                         &lt;enumeration value="application/vnd.powerpoint"/>
 *                         &lt;enumeration value="application/pdf"/>
 *                         &lt;enumeration value="application/vnd.openxmlformats-officedocument.wordprocessingml.document"/>
 *                         &lt;enumeration value="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
 *                         &lt;enumeration value="application/vnd.openxmlformats-officedocument.presentationml.presentation"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Store">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;pattern value="\d{1,2}"/>
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="AttachmentType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                         &lt;pattern value="\d{1,2}"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Document" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "body"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected DRSRequestHeader header;
    @XmlElement(required = true)
    protected Request.Body body;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link DRSRequestHeader }
     */
    public DRSRequestHeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link DRSRequestHeader }
     */
    public void setHeader(DRSRequestHeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return possible object is
     * {@link Request.Body }
     */
    public Request.Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is
     *              {@link Request.Body }
     */
    public void setBody(Request.Body value) {
        this.body = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Metadata" type="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_UD"/>
     *         &lt;element name="MimeType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="application/msword"/>
     *               &lt;enumeration value="application/vnd.ms-excel"/>
     *               &lt;enumeration value="application/vnd.ms-powerpoint"/>
     *               &lt;enumeration value="application/vnd.powerpoint"/>
     *               &lt;enumeration value="application/pdf"/>
     *               &lt;enumeration value="application/vnd.openxmlformats-officedocument.wordprocessingml.document"/>
     *               &lt;enumeration value="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"/>
     *               &lt;enumeration value="application/vnd.openxmlformats-officedocument.presentationml.presentation"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Store">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;pattern value="\d{1,2}"/>
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="AttachmentType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *               &lt;pattern value="\d{1,2}"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Document" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "metadata",
            "mimeType",
            "store",
            "attachmentType",
            "document"
    })
    public static class Body {

        @XmlElement(name = "Metadata", required = true)
        protected DRSMetaDataDefnUD metadata;
        @XmlElement(name = "MimeType", required = true)
        protected String mimeType;
        @XmlElement(name = "Store")
        protected int store;
        @XmlElement(name = "AttachmentType")
        protected int attachmentType;
        @XmlElement(name = "Document", required = true)
        protected byte[] document;

        /**
         * Gets the value of the metadata property.
         *
         * @return possible object is
         * {@link DRSMetaDataDefnUD }
         */
        public DRSMetaDataDefnUD getMetadata() {
            return metadata;
        }

        /**
         * Sets the value of the metadata property.
         *
         * @param value allowed object is
         *              {@link DRSMetaDataDefnUD }
         */
        public void setMetadata(DRSMetaDataDefnUD value) {
            this.metadata = value;
        }

        /**
         * Gets the value of the mimeType property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMimeType() {
            return mimeType;
        }

        /**
         * Sets the value of the mimeType property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMimeType(String value) {
            this.mimeType = value;
        }

        /**
         * Gets the value of the store property.
         */
        public int getStore() {
            return store;
        }

        /**
         * Sets the value of the store property.
         */
        public void setStore(int value) {
            this.store = value;
        }

        /**
         * Gets the value of the attachmentType property.
         */
        public int getAttachmentType() {
            return attachmentType;
        }

        /**
         * Sets the value of the attachmentType property.
         */
        public void setAttachmentType(int value) {
            this.attachmentType = value;
        }

        /**
         * Gets the value of the document property.
         *
         * @return possible object is
         * byte[]
         */
        public byte[] getDocument() {
            return document;
        }

        /**
         * Sets the value of the document property.
         *
         * @param value allowed object is
         *              byte[]
         */
        public void setDocument(byte[] value) {
            this.document = value;
        }

    }

}
