//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 08:29:06 AM GMT 
//


package uk.gov.govtalk.drs.common.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * Metadata Read Only
 * <p>
 * <p>Java class for DRS_MetaData_Defn_RO complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DRS_MetaData_Defn_RO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Int_RO"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Int_UD"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Int_RO"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Int_RW"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Int_Office_PO_Opt"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Link_and_CRN"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Int_UD"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_BenType_HarmFlag"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_OfficeId_DateReportGen"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Auto_Disposition_Flag"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Retention_Date_Data"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_REC"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_ClaimRef"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRS_MetaData_Defn_RO", propOrder = {
        "documentID",
        "businessUnitID",
        "classification",
        "documentType",
        "receiptDate",
        "scanDateTime",
        "indexDateTime",
        "scanBatchID",
        "scanEnvelopeID",
        "scanningCentreID",
        "scanDocumentID",
        "scannerOperatorID",
        "indexOperatorID",
        "nPages",
        "rejectRequestStatus",
        "rescanRequestIdentifier",
        "docsWithinEnvelope",
        "documentStatus",
        "lastUpdated",
        "rejectReason",
        "rescanResponse",
        "documentDate",
        "organisationName",
        "nino",
        "dateOfBirth",
        "surname",
        "forename",
        "postCode",
        "lobCaseID",
        "officePostcode",
        "linkData",
        "customerReferenceNumber",
        "documentSource",
        "issueDate",
        "harmfulIndicatorFlag",
        "benefitType",
        "officeID",
        "dateReportGenerated",
        "automaticDispositionStop",
        "generalHoldInterest",
        "overpaymentHoldInterest",
        "generalHoldDate",
        "overpaymentHoldDate",
        "holdReason",
        "externalContentIdentifier",
        "externalSource",
        "claimRef",
        "customerMobileNumber"
})
public class DRSMetaDataDefnRO {

    @XmlElement(name = "DocumentID", required = true)
    protected String documentID;
    @XmlElement(name = "BusinessUnitID")
    protected int businessUnitID;
    @XmlElement(name = "Classification")
    protected int classification;
    @XmlElement(name = "DocumentType")
    protected int documentType;
    @XmlElement(name = "ReceiptDate")
    protected String receiptDate;
    @XmlElement(name = "ScanDateTime")
    protected String scanDateTime;
    @XmlElement(name = "IndexDateTime")
    protected String indexDateTime;
    @XmlElement(name = "ScanBatchID")
    protected String scanBatchID;
    @XmlElement(name = "ScanEnvelopeID")
    protected String scanEnvelopeID;
    @XmlElement(name = "ScanningCentreID")
    protected String scanningCentreID;
    @XmlElement(name = "ScanDocumentID")
    protected String scanDocumentID;
    @XmlElement(name = "ScannerOperatorID")
    protected String scannerOperatorID;
    @XmlElement(name = "IndexOperatorID")
    protected String indexOperatorID;
    @XmlElement(name = "NPages")
    protected Integer nPages;
    @XmlElement(name = "RejectRequestStatus")
    protected Integer rejectRequestStatus;
    @XmlElement(name = "RescanRequestIdentifier")
    protected String rescanRequestIdentifier;
    @XmlElement(name = "DocsWithinEnvelope")
    protected Integer docsWithinEnvelope;
    @XmlElement(name = "DocumentStatus")
    protected String documentStatus;
    @XmlElement(name = "LastUpdated")
    protected String lastUpdated;
    @XmlElement(name = "RejectReason")
    protected Integer rejectReason;
    @XmlElement(name = "RescanResponse")
    protected Integer rescanResponse;
    @XmlElement(name = "DocumentDate")
    protected String documentDate;
    @XmlElement(name = "OrganisationName")
    protected Integer organisationName;
    @XmlElement(name = "NINO")
    protected NINO nino;
    @XmlElement(name = "DateOfBirth")
    protected String dateOfBirth;
    @XmlElement(name = "Surname")
    protected String surname;
    @XmlElement(name = "Forename")
    protected String forename;
    @XmlElement(name = "PostCode")
    protected String postCode;
    @XmlElement(name = "LOBCaseID")
    protected String lobCaseID;
    @XmlElement(name = "OfficePostcode")
    protected String officePostcode;
    @XmlElement(name = "LinkData")
    protected String linkData;
    @XmlElement(name = "CustomerReferenceNumber")
    protected String customerReferenceNumber;
    @XmlElement(name = "DocumentSource")
    protected int documentSource;
    @XmlElement(name = "IssueDate")
    protected String issueDate;
    @XmlElement(name = "HarmfulIndicatorFlag")
    protected Integer harmfulIndicatorFlag;
    @XmlElement(name = "BenefitType")
    protected Integer benefitType;
    @XmlElement(name = "OfficeID")
    protected String officeID;
    @XmlElement(name = "DateReportGenerated")
    protected String dateReportGenerated;
    @XmlElement(name = "AutomaticDispositionStop")
    protected Integer automaticDispositionStop;
    @XmlElement(name = "GeneralHoldInterest")
    protected Integer generalHoldInterest;
    @XmlElement(name = "OverpaymentHoldInterest")
    protected Integer overpaymentHoldInterest;
    @XmlElement(name = "GeneralHoldDate")
    protected String generalHoldDate;
    @XmlElement(name = "OverpaymentHoldDate")
    protected String overpaymentHoldDate;
    @XmlElement(name = "HoldReason")
    protected Integer holdReason;
    @XmlElement(name = "ExternalContentIdentifier")
    protected String externalContentIdentifier;
    @XmlElement(name = "ExternalSource")
    protected BigDecimal externalSource;
    @XmlElement(name = "ClaimRef")
    protected String claimRef;
    @XmlElement(name = "CustomerMobileNumber")
    protected String customerMobileNumber;

    /**
     * Gets the value of the documentID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocumentID() {
        return documentID;
    }

    /**
     * Sets the value of the documentID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentID(String value) {
        this.documentID = value;
    }

    /**
     * Gets the value of the businessUnitID property.
     */
    public int getBusinessUnitID() {
        return businessUnitID;
    }

    /**
     * Sets the value of the businessUnitID property.
     */
    public void setBusinessUnitID(int value) {
        this.businessUnitID = value;
    }

    /**
     * Gets the value of the classification property.
     */
    public int getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     */
    public void setClassification(int value) {
        this.classification = value;
    }

    /**
     * Gets the value of the documentType property.
     */
    public int getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     */
    public void setDocumentType(int value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the receiptDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReceiptDate() {
        return receiptDate;
    }

    /**
     * Sets the value of the receiptDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReceiptDate(String value) {
        this.receiptDate = value;
    }

    /**
     * Gets the value of the scanDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanDateTime() {
        return scanDateTime;
    }

    /**
     * Sets the value of the scanDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanDateTime(String value) {
        this.scanDateTime = value;
    }

    /**
     * Gets the value of the indexDateTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIndexDateTime() {
        return indexDateTime;
    }

    /**
     * Sets the value of the indexDateTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIndexDateTime(String value) {
        this.indexDateTime = value;
    }

    /**
     * Gets the value of the scanBatchID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanBatchID() {
        return scanBatchID;
    }

    /**
     * Sets the value of the scanBatchID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanBatchID(String value) {
        this.scanBatchID = value;
    }

    /**
     * Gets the value of the scanEnvelopeID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanEnvelopeID() {
        return scanEnvelopeID;
    }

    /**
     * Sets the value of the scanEnvelopeID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanEnvelopeID(String value) {
        this.scanEnvelopeID = value;
    }

    /**
     * Gets the value of the scanningCentreID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanningCentreID() {
        return scanningCentreID;
    }

    /**
     * Sets the value of the scanningCentreID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanningCentreID(String value) {
        this.scanningCentreID = value;
    }

    /**
     * Gets the value of the scanDocumentID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScanDocumentID() {
        return scanDocumentID;
    }

    /**
     * Sets the value of the scanDocumentID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScanDocumentID(String value) {
        this.scanDocumentID = value;
    }

    /**
     * Gets the value of the scannerOperatorID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getScannerOperatorID() {
        return scannerOperatorID;
    }

    /**
     * Sets the value of the scannerOperatorID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setScannerOperatorID(String value) {
        this.scannerOperatorID = value;
    }

    /**
     * Gets the value of the indexOperatorID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIndexOperatorID() {
        return indexOperatorID;
    }

    /**
     * Sets the value of the indexOperatorID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIndexOperatorID(String value) {
        this.indexOperatorID = value;
    }

    /**
     * Gets the value of the nPages property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getNPages() {
        return nPages;
    }

    /**
     * Sets the value of the nPages property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setNPages(Integer value) {
        this.nPages = value;
    }

    /**
     * Gets the value of the rejectRequestStatus property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getRejectRequestStatus() {
        return rejectRequestStatus;
    }

    /**
     * Sets the value of the rejectRequestStatus property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setRejectRequestStatus(Integer value) {
        this.rejectRequestStatus = value;
    }

    /**
     * Gets the value of the rescanRequestIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRescanRequestIdentifier() {
        return rescanRequestIdentifier;
    }

    /**
     * Sets the value of the rescanRequestIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRescanRequestIdentifier(String value) {
        this.rescanRequestIdentifier = value;
    }

    /**
     * Gets the value of the docsWithinEnvelope property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getDocsWithinEnvelope() {
        return docsWithinEnvelope;
    }

    /**
     * Sets the value of the docsWithinEnvelope property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setDocsWithinEnvelope(Integer value) {
        this.docsWithinEnvelope = value;
    }

    /**
     * Gets the value of the documentStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocumentStatus() {
        return documentStatus;
    }

    /**
     * Sets the value of the documentStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentStatus(String value) {
        this.documentStatus = value;
    }

    /**
     * Gets the value of the lastUpdated property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the value of the lastUpdated property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastUpdated(String value) {
        this.lastUpdated = value;
    }

    /**
     * Gets the value of the rejectReason property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getRejectReason() {
        return rejectReason;
    }

    /**
     * Sets the value of the rejectReason property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setRejectReason(Integer value) {
        this.rejectReason = value;
    }

    /**
     * Gets the value of the rescanResponse property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getRescanResponse() {
        return rescanResponse;
    }

    /**
     * Sets the value of the rescanResponse property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setRescanResponse(Integer value) {
        this.rescanResponse = value;
    }

    /**
     * Gets the value of the documentDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocumentDate() {
        return documentDate;
    }

    /**
     * Sets the value of the documentDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentDate(String value) {
        this.documentDate = value;
    }

    /**
     * Gets the value of the organisationName property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getOrganisationName() {
        return organisationName;
    }

    /**
     * Sets the value of the organisationName property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setOrganisationName(Integer value) {
        this.organisationName = value;
    }

    /**
     * Gets the value of the nino property.
     *
     * @return possible object is
     * {@link NINO }
     */
    public NINO getNINO() {
        return nino;
    }

    /**
     * Sets the value of the nino property.
     *
     * @param value allowed object is
     *              {@link NINO }
     */
    public void setNINO(NINO value) {
        this.nino = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the surname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the forename property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getForename() {
        return forename;
    }

    /**
     * Sets the value of the forename property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForename(String value) {
        this.forename = value;
    }

    /**
     * Gets the value of the postCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the lobCaseID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLOBCaseID() {
        return lobCaseID;
    }

    /**
     * Sets the value of the lobCaseID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLOBCaseID(String value) {
        this.lobCaseID = value;
    }

    /**
     * Gets the value of the officePostcode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOfficePostcode() {
        return officePostcode;
    }

    /**
     * Sets the value of the officePostcode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOfficePostcode(String value) {
        this.officePostcode = value;
    }

    /**
     * Gets the value of the linkData property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLinkData() {
        return linkData;
    }

    /**
     * Sets the value of the linkData property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLinkData(String value) {
        this.linkData = value;
    }

    /**
     * Gets the value of the customerReferenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerReferenceNumber() {
        return customerReferenceNumber;
    }

    /**
     * Sets the value of the customerReferenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerReferenceNumber(String value) {
        this.customerReferenceNumber = value;
    }

    /**
     * Gets the value of the documentSource property.
     */
    public int getDocumentSource() {
        return documentSource;
    }

    /**
     * Sets the value of the documentSource property.
     */
    public void setDocumentSource(int value) {
        this.documentSource = value;
    }

    /**
     * Gets the value of the issueDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the harmfulIndicatorFlag property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getHarmfulIndicatorFlag() {
        return harmfulIndicatorFlag;
    }

    /**
     * Sets the value of the harmfulIndicatorFlag property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setHarmfulIndicatorFlag(Integer value) {
        this.harmfulIndicatorFlag = value;
    }

    /**
     * Gets the value of the benefitType property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getBenefitType() {
        return benefitType;
    }

    /**
     * Sets the value of the benefitType property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setBenefitType(Integer value) {
        this.benefitType = value;
    }

    /**
     * Gets the value of the officeID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOfficeID() {
        return officeID;
    }

    /**
     * Sets the value of the officeID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOfficeID(String value) {
        this.officeID = value;
    }

    /**
     * Gets the value of the dateReportGenerated property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateReportGenerated() {
        return dateReportGenerated;
    }

    /**
     * Sets the value of the dateReportGenerated property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateReportGenerated(String value) {
        this.dateReportGenerated = value;
    }

    /**
     * Gets the value of the automaticDispositionStop property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getAutomaticDispositionStop() {
        return automaticDispositionStop;
    }

    /**
     * Sets the value of the automaticDispositionStop property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setAutomaticDispositionStop(Integer value) {
        this.automaticDispositionStop = value;
    }

    /**
     * Gets the value of the generalHoldInterest property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getGeneralHoldInterest() {
        return generalHoldInterest;
    }

    /**
     * Sets the value of the generalHoldInterest property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setGeneralHoldInterest(Integer value) {
        this.generalHoldInterest = value;
    }

    /**
     * Gets the value of the overpaymentHoldInterest property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getOverpaymentHoldInterest() {
        return overpaymentHoldInterest;
    }

    /**
     * Sets the value of the overpaymentHoldInterest property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setOverpaymentHoldInterest(Integer value) {
        this.overpaymentHoldInterest = value;
    }

    /**
     * Gets the value of the generalHoldDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGeneralHoldDate() {
        return generalHoldDate;
    }

    /**
     * Sets the value of the generalHoldDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGeneralHoldDate(String value) {
        this.generalHoldDate = value;
    }

    /**
     * Gets the value of the overpaymentHoldDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOverpaymentHoldDate() {
        return overpaymentHoldDate;
    }

    /**
     * Sets the value of the overpaymentHoldDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOverpaymentHoldDate(String value) {
        this.overpaymentHoldDate = value;
    }

    /**
     * Gets the value of the holdReason property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getHoldReason() {
        return holdReason;
    }

    /**
     * Sets the value of the holdReason property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setHoldReason(Integer value) {
        this.holdReason = value;
    }

    /**
     * Gets the value of the externalContentIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExternalContentIdentifier() {
        return externalContentIdentifier;
    }

    /**
     * Sets the value of the externalContentIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalContentIdentifier(String value) {
        this.externalContentIdentifier = value;
    }

    /**
     * Gets the value of the externalSource property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getExternalSource() {
        return externalSource;
    }

    /**
     * Sets the value of the externalSource property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setExternalSource(BigDecimal value) {
        this.externalSource = value;
    }

    /**
     * Gets the value of the claimRef property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClaimRef() {
        return claimRef;
    }

    /**
     * Sets the value of the claimRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClaimRef(String value) {
        this.claimRef = value;
    }

    /**
     * Gets the value of the customerMobileNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerMobileNumber() {
        return this.customerMobileNumber;
    }

    /**
     * Sets the value of the customerMobileNumber property.
     *
     * @return allowed object is
     * {@link String }
     */
    public void setCustomerMobileNumber(String customerMobileNumber) {
        this.customerMobileNumber = customerMobileNumber;
    }
}
