//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 08:29:06 AM GMT 
//


package uk.gov.govtalk.drs.common.metadata;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadata Upload Document
 * <p>
 * <p>Java class for DRS_MetaData_Defn_UD complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DRS_MetaData_Defn_UD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Int_UD"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Int_RW_Update"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Int_Office_PO_Opt_Update"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Core_Link_and_CRN_Update"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_BenType_HarmFlag"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_ClaimRef"/>
 *         &lt;group ref="{http://www.govtalk.gov.uk/drs/common/metadata}DRS_MetaData_Defn_Int_UD_Update"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRS_MetaData_Defn_UD", propOrder = {
        "businessUnitID",
        "classification",
        "documentType",
        "nino",
        "dateOfBirth",
        "surname",
        "forename",
        "postCode",
        "lobCaseID",
        "officePostcode",
        "linkData",
        "customerReferenceNumber",
        "harmfulIndicatorFlag",
        "benefitType",
        "claimRef",
        "customerMobileNumber",
        "documentSource",
        "issueDate"
})
public class DRSMetaDataDefnUD {

    @XmlElement(name = "BusinessUnitID")
    protected Integer businessUnitID;
    @XmlElement(name = "Classification")
    protected Integer classification;
    @XmlElement(name = "DocumentType")
    protected Integer documentType;
    @XmlElement(name = "NINO")
    protected NINO nino;
    @XmlElement(name = "DateOfBirth")
    protected String dateOfBirth;
    @XmlElement(name = "Surname")
    @JsonProperty(required = true)
    protected String surname;
    @XmlElement(name = "Forename")
    protected String forename;
    @XmlElement(name = "PostCode")
    protected String postCode;
    @XmlElement(name = "LOBCaseID")
    protected String lobCaseID;
    @XmlElement(name = "OfficePostcode")
    protected String officePostcode;
    @XmlElement(name = "LinkData")
    protected String linkData;
    @XmlElement(name = "CustomerReferenceNumber")
    protected String customerReferenceNumber;
    @XmlElement(name = "HarmfulIndicatorFlag")
    protected Integer harmfulIndicatorFlag;
    @XmlElement(name = "BenefitType")
    protected Integer benefitType;
    @XmlElement(name = "ClaimRef")
    protected String claimRef;
    @XmlElement(name = "CustomerMobileNumber")
    protected String customerMobileNumber;
    @XmlElement(name = "DocumentSource")
    protected Integer documentSource;
    @XmlElement(name = "IssueDate")
    protected String issueDate;

    /**
     * Gets the value of the businessUnitID property.
     */
    public Integer getBusinessUnitID() {
        return businessUnitID;
    }

    /**
     * Sets the value of the businessUnitID property.
     */
    public void setBusinessUnitID(Integer value) {
        this.businessUnitID = value;
    }

    /**
     * Gets the value of the classification property.
     */
    public Integer getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     */
    public void setClassification(Integer value) {
        this.classification = value;
    }

    /**
     * Gets the value of the documentType property.
     */
    public Integer getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     */
    public void setDocumentType(Integer value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the nino property.
     *
     * @return possible object is
     * {@link NINO }
     */
    public NINO getNINO() {
        return nino;
    }

    /**
     * Sets the value of the nino property.
     *
     * @param value allowed object is
     *              {@link NINO }
     */
    public void setNINO(NINO value) {
        this.nino = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the surname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the forename property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getForename() {
        return forename;
    }

    /**
     * Sets the value of the forename property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setForename(String value) {
        this.forename = value;
    }

    /**
     * Gets the value of the postCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the lobCaseID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLOBCaseID() {
        return lobCaseID;
    }

    /**
     * Sets the value of the lobCaseID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLOBCaseID(String value) {
        this.lobCaseID = value;
    }

    /**
     * Gets the value of the officePostcode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOfficePostcode() {
        return officePostcode;
    }

    /**
     * Sets the value of the officePostcode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOfficePostcode(String value) {
        this.officePostcode = value;
    }

    /**
     * Gets the value of the linkData property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLinkData() {
        return linkData;
    }

    /**
     * Sets the value of the linkData property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLinkData(String value) {
        this.linkData = value;
    }

    /**
     * Gets the value of the customerReferenceNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerReferenceNumber() {
        return customerReferenceNumber;
    }

    /**
     * Sets the value of the customerReferenceNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCustomerReferenceNumber(String value) {
        this.customerReferenceNumber = value;
    }

    /**
     * Gets the value of the harmfulIndicatorFlag property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getHarmfulIndicatorFlag() {
        return harmfulIndicatorFlag;
    }

    /**
     * Sets the value of the harmfulIndicatorFlag property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setHarmfulIndicatorFlag(Integer value) {
        this.harmfulIndicatorFlag = value;
    }

    /**
     * Gets the value of the benefitType property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getBenefitType() {
        return benefitType;
    }

    /**
     * Sets the value of the benefitType property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setBenefitType(Integer value) {
        this.benefitType = value;
    }

    /**
     * Gets the value of the claimRef property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClaimRef() {
        return claimRef;
    }

    /**
     * Sets the value of the claimRef property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClaimRef(String value) {
        this.claimRef = value;
    }

    /**
     * Gets the value of the documentSource property.
     */
    public Integer getDocumentSource() {
        return documentSource;
    }

    /**
     * Sets the value of the documentSource property.
     */
    public void setDocumentSource(Integer value) {
        this.documentSource = value;
    }

    /**
     * Gets the value of the issueDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIssueDate(String value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the customerMobileNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCustomerMobileNumber() {
        return this.customerMobileNumber;
    }

    /**
     * Sets the value of the customerMobileNumber property.
     *
     * @return allowed object is
     * {@link String }
     */
    public void setCustomerMobileNumber(String customerMobileNumber) {
        this.customerMobileNumber = customerMobileNumber;
    }
}
