//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 08:29:06 AM GMT 
//


package uk.gov.govtalk.drs.common.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The header element for the DRS Document Upload response
 * <p>
 * <p>Java class for DRS_Response_Header complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DRS_Response_Header">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.govtalk.gov.uk/drs/common/response}versionType"/>
 *         &lt;element name="SuccessIndicator">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;pattern value="\d"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReturnCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;pattern value="\d{1,4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReasonCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRS_Response_Header", propOrder = {
        "version",
        "successIndicator",
        "returnCode",
        "reasonCode"
})
public class DRSResponseHeader {

    @XmlElement(name = "Version")
    protected float version;
    @XmlElement(name = "SuccessIndicator")
    protected int successIndicator;
    @XmlElement(name = "ReturnCode")
    protected int returnCode;
    @XmlElement(name = "ReasonCode")
    protected int reasonCode;

    /**
     * Gets the value of the version property.
     */
    public float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     */
    public void setVersion(float value) {
        this.version = value;
    }

    /**
     * Gets the value of the successIndicator property.
     */
    public int getSuccessIndicator() {
        return successIndicator;
    }

    /**
     * Sets the value of the successIndicator property.
     */
    public void setSuccessIndicator(int value) {
        this.successIndicator = value;
    }

    /**
     * Gets the value of the returnCode property.
     */
    public int getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     */
    public void setReturnCode(int value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the reasonCode property.
     */
    public int getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     */
    public void setReasonCode(int value) {
        this.reasonCode = value;
    }

}
