//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 08:22:42 AM GMT 
//


package uk.gov.govtalk.drs.common.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DRS_Request_Header complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DRS_Request_Header">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Version" type="{http://www.govtalk.gov.uk/drs/common/request}versionType"/>
 *         &lt;element name="UserIdentifier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UserName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AuditHeader" type="{http://www.govtalk.gov.uk/drs/common/request}DRS_ID_Audit_Defn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DRS_Request_Header", propOrder = {
        "version",
        "userIdentifier",
        "userName",
        "auditHeader"
})
public class DRSRequestHeader {

    @XmlElement(name = "Version")
    protected float version;
    @XmlElement(name = "UserIdentifier")
    protected String userIdentifier;
    @XmlElement(name = "UserName")
    protected String userName;
    @XmlElement(name = "AuditHeader", required = true)
    protected DRSIDAuditDefn auditHeader;

    /**
     * Gets the value of the version property.
     */
    public float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     */
    public void setVersion(float value) {
        this.version = value;
    }

    /**
     * Gets the value of the userIdentifier property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserIdentifier() {
        return userIdentifier;
    }

    /**
     * Sets the value of the userIdentifier property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserIdentifier(String value) {
        this.userIdentifier = value;
    }

    /**
     * Gets the value of the userName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the auditHeader property.
     *
     * @return possible object is
     * {@link DRSIDAuditDefn }
     */
    public DRSIDAuditDefn getAuditHeader() {
        return auditHeader;
    }

    /**
     * Sets the value of the auditHeader property.
     *
     * @param value allowed object is
     *              {@link DRSIDAuditDefn }
     */
    public void setAuditHeader(DRSIDAuditDefn value) {
        this.auditHeader = value;
    }

}
